// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpanSight.Core.Data;

#nullable disable

namespace SpanSight.Core.Data.Migrations
{
    [DbContext(typeof(SpanSightDbContext))]
    [Migration("20260717122005_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpanSight.Core.Data.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<int>("RowsLoaded")
                        .HasColumnType("integer")
                        .HasColumnName("rows_loaded");

                    b.Property<int>("RowsQuarantined")
                        .HasColumnType("integer")
                        .HasColumnName("rows_quarantined");

                    b.Property<int>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<int>("SnapshotYear")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_year");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_file");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_sha256");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceSha256", "SnapshotYear");

                    b.ToTable("ingestion_run", "ops");
                });

            modelBuilder.Entity("SpanSight.Core.Data.QuarantineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingestion_run_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_line");

                    b.PrimitiveCollection<List<string>>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reasons");

                    b.Property<string>("StateCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("state_code");

                    b.Property<string>("StructureNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("structure_number");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("StateCode");

                    b.ToTable("quarantine_row", "quarantine");
                });

            modelBuilder.Entity("SpanSight.Core.Domain.Bridge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Adt")
                        .HasColumnType("integer")
                        .HasColumnName("adt");

                    b.Property<string>("ConditionClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("condition_class");

                    b.Property<string>("CountyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("county_code");

                    b.Property<string>("CulvertCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("culvert_condition");

                    b.Property<string>("DeckCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("deck_condition");

                    b.Property<string>("DesignCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("design_code");

                    b.Property<string>("FacilityCarried")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("facility_carried");

                    b.Property<string>("FeaturesIntersected")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("features_intersected");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("LocationText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location_text");

                    b.Property<int?>("LowestRating")
                        .HasColumnType("integer")
                        .HasColumnName("lowest_rating");

                    b.Property<string>("MaterialCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("material_code");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("record_type");

                    b.Property<int>("SnapshotYear")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_year");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_format");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<decimal?>("StructureLengthMeters")
                        .HasPrecision(9, 1)
                        .HasColumnType("numeric(9,1)")
                        .HasColumnName("structure_length_meters");

                    b.Property<string>("StructureNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("structure_number");

                    b.Property<string>("SubstructureCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("substructure_condition");

                    b.Property<string>("SuperstructureCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("superstructure_condition");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id");

                    b.HasIndex("Adt");

                    b.HasIndex("ConditionClass");

                    b.HasIndex("DesignCode");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MaterialCode");

                    b.HasIndex("YearBuilt");

                    b.HasIndex("StateCode", "CountyCode");

                    b.HasIndex("StateCode", "StructureNumber", "RecordType")
                        .IsUnique();

                    b.ToTable("bridge", "core");
                });

            modelBuilder.Entity("SpanSight.Core.Data.QuarantineRow", b =>
                {
                    b.HasOne("SpanSight.Core.Data.IngestionRun", "IngestionRun")
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });
#pragma warning restore 612, 618
        }
    }
}
