// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpanSight.Core.Data;

#nullable disable

namespace SpanSight.Core.Data.Migrations
{
    [DbContext(typeof(SpanSightDbContext))]
    [Migration("20260727205527_RankingCoveringIndex")]
    partial class RankingCoveringIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpanSight.Core.Analytics.BridgeConditionSeries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("FirstYear")
                        .HasColumnType("smallint")
                        .HasColumnName("first_year");

                    b.Property<short>("LastYear")
                        .HasColumnType("smallint")
                        .HasColumnName("last_year");

                    b.Property<short>("ObservedYears")
                        .HasColumnType("smallint")
                        .HasColumnName("observed_years");

                    b.Property<string>("Ratings")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ratings");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("StructureNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("structure_number");

                    b.Property<long>("TrendRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("trend_run_id");

                    b.HasKey("Id");

                    b.HasIndex("TrendRunId");

                    b.HasIndex("StateCode", "StructureNumber")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("StateCode", "StructureNumber"), new[] { "FirstYear", "LastYear", "ObservedYears", "Ratings" });

                    b.ToTable("bridge_condition_series", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CensusCounty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcsPeriod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("acs_period");

                    b.Property<string>("AcsTable")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("acs_table");

                    b.Property<short?>("AcsVintage")
                        .HasColumnType("smallint")
                        .HasColumnName("acs_vintage");

                    b.Property<string>("CountyFips")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("county_fips");

                    b.Property<long>("CountyJoinRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("county_join_run_id");

                    b.Property<long>("LandAreaM2")
                        .HasColumnType("bigint")
                        .HasColumnName("land_area_m2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameLsad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_lsad");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<long?>("PopulationMoe")
                        .HasColumnType("bigint")
                        .HasColumnName("population_moe");

                    b.Property<string>("StateFips")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_fips");

                    b.Property<short>("TigerVintage")
                        .HasColumnType("smallint")
                        .HasColumnName("tiger_vintage");

                    b.Property<long>("WaterAreaM2")
                        .HasColumnType("bigint")
                        .HasColumnName("water_area_m2");

                    b.HasKey("Id");

                    b.HasIndex("CountyFips")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CountyFips"), new[] { "StateFips", "Name", "NameLsad", "Population", "PopulationMoe", "AcsVintage", "AcsPeriod", "TigerVintage" });

                    b.HasIndex("CountyJoinRunId");

                    b.HasIndex("StateFips");

                    b.ToTable("census_county", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.ConditionRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Fair")
                        .HasColumnType("integer")
                        .HasColumnName("fair");

                    b.Property<string>("Fips")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("fips");

                    b.Property<int>("Good")
                        .HasColumnType("integer")
                        .HasColumnName("good");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("level");

                    b.Property<int>("Poor")
                        .HasColumnType("integer")
                        .HasColumnName("poor");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<long>("TrendRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("trend_run_id");

                    b.Property<int>("Unknown")
                        .HasColumnType("integer")
                        .HasColumnName("unknown");

                    b.Property<short>("VintageYear")
                        .HasColumnType("smallint")
                        .HasColumnName("vintage_year");

                    b.HasKey("Id");

                    b.HasIndex("TrendRunId");

                    b.HasIndex("Level", "Fips", "VintageYear")
                        .IsUnique();

                    b.ToTable("condition_rollup", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CountyJoinDisagreement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bridges")
                        .HasColumnType("integer")
                        .HasColumnName("bridges");

                    b.Property<string>("CountyFips")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("county_fips");

                    b.Property<long>("CountyJoinRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("county_join_run_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("NbiCountyFips")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nbi_county_fips");

                    b.Property<bool?>("NbiFipsInTiger")
                        .HasColumnType("boolean")
                        .HasColumnName("nbi_fips_in_tiger");

                    b.HasKey("Id");

                    b.HasIndex("CountyJoinRunId");

                    b.HasIndex("NbiCountyFips", "CountyFips")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("NbiCountyFips", "CountyFips"), false);

                    b.ToTable("county_join_disagreement", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CountyJoinMiss", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CountyJoinRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("county_join_run_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("NbiCountyFips")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nbi_county_fips");

                    b.Property<string>("NearestCountyFips")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nearest_county_fips");

                    b.Property<long?>("NearestDistanceMeters")
                        .HasColumnType("bigint")
                        .HasColumnName("nearest_distance_meters");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("record_type");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("StructureNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("structure_number");

                    b.Property<int>("TouchingCounties")
                        .HasColumnType("integer")
                        .HasColumnName("touching_counties");

                    b.HasKey("Id");

                    b.HasIndex("CountyJoinRunId");

                    b.HasIndex("StateCode", "StructureNumber", "RecordType")
                        .IsUnique();

                    b.ToTable("county_join_miss", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CountyJoinRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Agree")
                        .HasColumnType("bigint")
                        .HasColumnName("agree");

                    b.Property<long>("Bridges")
                        .HasColumnType("bigint")
                        .HasColumnName("bridges");

                    b.Property<string>("CatalogSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_sha256");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<string>("ContainmentPredicate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("containment_predicate");

                    b.Property<int>("Counties")
                        .HasColumnType("integer")
                        .HasColumnName("counties");

                    b.Property<int>("CountiesWithoutPopulation")
                        .HasColumnType("integer")
                        .HasColumnName("counties_without_population");

                    b.Property<long>("CountyNotPublished")
                        .HasColumnType("bigint")
                        .HasColumnName("county_not_published");

                    b.Property<long>("DifferentCountySameState")
                        .HasColumnType("bigint")
                        .HasColumnName("different_county_same_state");

                    b.Property<long>("DifferentState")
                        .HasColumnType("bigint")
                        .HasColumnName("different_state");

                    b.Property<long>("DisagreementBridges")
                        .HasColumnType("bigint")
                        .HasColumnName("disagreement_bridges");

                    b.Property<int>("Disagreements")
                        .HasColumnType("integer")
                        .HasColumnName("disagreements");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<string>("JobRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_run_id");

                    b.Property<long>("Matched")
                        .HasColumnType("bigint")
                        .HasColumnName("matched");

                    b.Property<string>("MethodVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method_version");

                    b.Property<int>("Misses")
                        .HasColumnType("integer")
                        .HasColumnName("misses");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("Structures")
                        .HasColumnType("bigint")
                        .HasColumnName("structures");

                    b.Property<long>("StructuresMatched")
                        .HasColumnType("bigint")
                        .HasColumnName("structures_matched");

                    b.Property<long>("Unmatched")
                        .HasColumnType("bigint")
                        .HasColumnName("unmatched");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId")
                        .IsUnique();

                    b.ToTable("county_join_run", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.DeteriorationMatrixCell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("component");

                    b.Property<long>("DeteriorationRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("deterioration_run_id");

                    b.Property<short>("FromRating")
                        .HasColumnType("smallint")
                        .HasColumnName("from_rating");

                    b.Property<string>("MaterialGroup")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("material_group");

                    b.Property<int>("Pairs")
                        .HasColumnType("integer")
                        .HasColumnName("pairs");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<short>("ToRating")
                        .HasColumnType("smallint")
                        .HasColumnName("to_rating");

                    b.Property<string>("TypeGroup")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type_group");

                    b.HasKey("Id");

                    b.HasIndex("DeteriorationRunId");

                    b.HasIndex("Component", "TypeGroup", "MaterialGroup", "Region", "FromRating", "ToRating")
                        .IsUnique();

                    b.ToTable("deterioration_matrix_cell", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.DeteriorationMatrixRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("component");

                    b.Property<long>("DeteriorationRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("deterioration_run_id");

                    b.Property<short>("FirstFromYear")
                        .HasColumnType("smallint")
                        .HasColumnName("first_from_year");

                    b.Property<short>("FromRating")
                        .HasColumnType("smallint")
                        .HasColumnName("from_rating");

                    b.Property<short>("LastFromYear")
                        .HasColumnType("smallint")
                        .HasColumnName("last_from_year");

                    b.Property<string>("MaterialGroup")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("material_group");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<int>("RowTotal")
                        .HasColumnType("integer")
                        .HasColumnName("row_total");

                    b.Property<string>("TypeGroup")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type_group");

                    b.Property<short>("YearPairsObserved")
                        .HasColumnType("smallint")
                        .HasColumnName("year_pairs_observed");

                    b.HasKey("Id");

                    b.HasIndex("DeteriorationRunId");

                    b.HasIndex("Component", "TypeGroup", "MaterialGroup", "Region", "FromRating")
                        .IsUnique();

                    b.ToTable("deterioration_matrix_row", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.DeteriorationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CatalogSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_sha256");

                    b.Property<int>("Cells")
                        .HasColumnType("integer")
                        .HasColumnName("cells");

                    b.Property<int>("Cohorts")
                        .HasColumnType("integer")
                        .HasColumnName("cohorts");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<long>("ComponentPairs")
                        .HasColumnType("bigint")
                        .HasColumnName("component_pairs");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<short>("FirstYear")
                        .HasColumnType("smallint")
                        .HasColumnName("first_year");

                    b.Property<string>("JobRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_run_id");

                    b.Property<short>("LastYear")
                        .HasColumnType("smallint")
                        .HasColumnName("last_year");

                    b.Property<int>("MatrixRows")
                        .HasColumnType("integer")
                        .HasColumnName("matrix_rows");

                    b.Property<string>("MethodologyVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("methodology_version");

                    b.Property<int>("RowsBelowFloor")
                        .HasColumnType("integer")
                        .HasColumnName("rows_below_floor");

                    b.Property<int>("SampleFloor")
                        .HasColumnType("integer")
                        .HasColumnName("sample_floor");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("StructurePairs")
                        .HasColumnType("bigint")
                        .HasColumnName("structure_pairs");

                    b.Property<int>("YearPairs")
                        .HasColumnType("integer")
                        .HasColumnName("year_pairs");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId")
                        .IsUnique();

                    b.ToTable("deterioration_run", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.TrendRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bridges")
                        .HasColumnType("integer")
                        .HasColumnName("bridges");

                    b.Property<string>("CatalogSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_sha256");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<short>("FirstYear")
                        .HasColumnType("smallint")
                        .HasColumnName("first_year");

                    b.Property<string>("JobRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_run_id");

                    b.Property<short>("LastYear")
                        .HasColumnType("smallint")
                        .HasColumnName("last_year");

                    b.Property<long>("Observations")
                        .HasColumnType("bigint")
                        .HasColumnName("observations");

                    b.Property<int>("RollupRows")
                        .HasColumnType("integer")
                        .HasColumnName("rollup_rows");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Vintages")
                        .HasColumnType("integer")
                        .HasColumnName("vintages");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId")
                        .IsUnique();

                    b.ToTable("trend_run", "analytics");
                });

            modelBuilder.Entity("SpanSight.Core.Data.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<int>("RowsLoaded")
                        .HasColumnType("integer")
                        .HasColumnName("rows_loaded");

                    b.Property<int>("RowsQuarantined")
                        .HasColumnType("integer")
                        .HasColumnName("rows_quarantined");

                    b.Property<int>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<int>("SnapshotYear")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_year");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_file");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_sha256");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceSha256", "SnapshotYear");

                    b.ToTable("ingestion_run", "ops");
                });

            modelBuilder.Entity("SpanSight.Core.Data.QuarantineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingestion_run_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_line");

                    b.PrimitiveCollection<List<string>>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reasons");

                    b.Property<string>("StateCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("state_code");

                    b.Property<string>("StructureNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("structure_number");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("StateCode");

                    b.ToTable("quarantine_row", "quarantine");
                });

            modelBuilder.Entity("SpanSight.Core.Domain.Bridge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Adt")
                        .HasColumnType("integer")
                        .HasColumnName("adt");

                    b.Property<string>("ConditionClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("condition_class");

                    b.Property<string>("CountyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("county_code");

                    b.Property<string>("CulvertCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("culvert_condition");

                    b.Property<string>("DeckCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("deck_condition");

                    b.Property<string>("DesignCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("design_code");

                    b.Property<string>("FacilityCarried")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("facility_carried");

                    b.Property<string>("FeaturesIntersected")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("features_intersected");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("LocationText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location_text");

                    b.Property<int?>("LowestRating")
                        .HasColumnType("integer")
                        .HasColumnName("lowest_rating");

                    b.Property<string>("MaterialCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("material_code");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("record_type");

                    b.Property<int>("SnapshotYear")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_year");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_format");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<decimal?>("StructureLengthMeters")
                        .HasPrecision(9, 1)
                        .HasColumnType("numeric(9,1)")
                        .HasColumnName("structure_length_meters");

                    b.Property<string>("StructureNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("structure_number");

                    b.Property<string>("SubstructureCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("substructure_condition");

                    b.Property<string>("SuperstructureCondition")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("superstructure_condition");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id");

                    b.HasIndex("Adt");

                    b.HasIndex("ConditionClass");

                    b.HasIndex("DesignCode");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MaterialCode");

                    b.HasIndex("RecordType")
                        .HasDatabaseName("ix_bridge_ranking");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecordType"), new[] { "StateCode", "CountyCode", "DesignCode", "MaterialCode", "ConditionClass" });

                    b.HasIndex("YearBuilt");

                    b.HasIndex("StateCode", "CountyCode");

                    b.HasIndex("StateCode", "StructureNumber", "RecordType")
                        .IsUnique();

                    b.ToTable("bridge", "core");
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.BridgeConditionSeries", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.TrendRun", null)
                        .WithMany()
                        .HasForeignKey("TrendRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CensusCounty", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.CountyJoinRun", null)
                        .WithMany()
                        .HasForeignKey("CountyJoinRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.ConditionRollup", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.TrendRun", null)
                        .WithMany()
                        .HasForeignKey("TrendRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CountyJoinDisagreement", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.CountyJoinRun", null)
                        .WithMany()
                        .HasForeignKey("CountyJoinRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.CountyJoinMiss", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.CountyJoinRun", null)
                        .WithMany()
                        .HasForeignKey("CountyJoinRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.DeteriorationMatrixCell", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.DeteriorationRun", null)
                        .WithMany()
                        .HasForeignKey("DeteriorationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Analytics.DeteriorationMatrixRow", b =>
                {
                    b.HasOne("SpanSight.Core.Analytics.DeteriorationRun", null)
                        .WithMany()
                        .HasForeignKey("DeteriorationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpanSight.Core.Data.QuarantineRow", b =>
                {
                    b.HasOne("SpanSight.Core.Data.IngestionRun", "IngestionRun")
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });
#pragma warning restore 612, 618
        }
    }
}
